javac services/UtilHelper.java
javac RestController.java
javac UploadFolder.java
javac GetBigPic.java
javac GetOnePic.java
javac groupPicBrowse.java
javac myPicBrowse.java
javac PictureBrowse.java
javac publicPicBrowse.java